### ISSUE TITLE
auditory stim presentation not working on windows

### ISSUE THREAD

**Issue by JohnGriffiths** [NeuroTechX/eeg-notebooks_v0.1#1]
Am currently getting the following error with auditory stim presentation in windows

```python

> python stimulus_presentation/generate_Auditory_P300.py

...

...

(base) C:\Users\John\GitBash\eeg-notebooks>python stimulus_presentation/generate_Auditory_P300.py
Traceback (most recent call last):
  File "stimulus_presentation/generate_Auditory_P300.py", line 40, in <module>
    aud1 = sound.Sound('C', octave=5, sampleRate=44100, secs=0.2, bits=8)
TypeError: __init__() got an unexpected keyword argument 'bits'
2.0765  INFO    Loaded SoundDevice with PortAudio V19.6.0-devel, revision 396fe4b6699ae929d3a685b3ef8a7e97396139a4
2.0772  INFO    sound is using audioLib: sounddevice
```

Have put a [fix attempt on new branch](https://github.com/NeuroTechX/eeg-notebooks/commit/235fdc148b1ec4df7d6e319d5a8f52169f8ba3af), removing the `bits` argument. But doesn't really fix the problem (get a few sounds and then errors).

**Comment by royyannick** [comment]
Are you still having the issue?
What version of Python, Psychopy and Windows?

**Comment by JohnGriffiths** [comment]
This was on windows 10 w/python 2.7

However the machine I was doing this on has now died. Getting a new one soon. 

Will take another look then. 

Have you been able to get auditory stim working ok on windows?

**Comment by JohnGriffiths** [comment]
This now seems to be working ok. c.f. the auditory evoked response notebooks in examples and sandbox folders.
