### ISSUE TITLE
[HowTo]EEG Analysis across many subjects with cross validation

### ISSUE THREAD

**Issue by akatav** [NeuroTechX/eeg-notebooks_v0.1#20]
Hi,
Your examples are very helpful. Especially, i am looking at this one - https://github.com/NeuroTechX/eeg-notebooks/blob/master/notebooks/SSVEP.ipynb

I am seeing that the dataset actually contains data only from 1 person (subject). I am unable to find any examples of MNE and ML analysis applied to a group of subjects and being used for classification&prediction.
Can you please give an example of this? For ex, if we have resting state EEG from 10 normal and 10 MCI subjects each with n_channels * n_times (n_times is the sample points, it is different for every subject). Is it possible to fit a model and predict (by cross validation) MCI or Normal for a given individual EEG signal?

**Comment by JohnGriffiths** [comment]
Hi Akatav. 

Thanks a lot for your interest. 

Indeed you are correct - there are not currently any ML group classification / prediction examples in eeg-notebooks. 

If you would like to contribute data and analysis code for such an example, that would be superb. 

For more info and worked examples of these approaches in a neuroimaging context, I would recommend you check out the *nilearn* and *mne-python* libraries and associated documentation.

**Comment by akatav** [comment]
@JohnGriffiths  oh ok, sure, i'll try. thank you v much for your kind reply.
