### ISSUE TITLE
lsl-record.py on mac

### ISSUE THREAD

**Issue by amandakeasson** [NeuroTechX/eeg-notebooks_v0.1#9]
lsl-record.py, line 35:
marker_streams = resolve_byprop('name', 'Markers', timeout=2)

The timeout period was not long enough when I ran this on my Macbook, so the marker stream was not found.

Increasing the timeout period to 10s fixed the problem.

**Comment by jdpigeon** [comment]
I believe this was resolved: https://github.com/alexandrebarachant/muse-lsl/issues/45
